name:        wreq-stringless
version:     0.5.1.0
synopsis:    Simple wrapper to use wreq without Strings
author:      Juergen Keck
maintainer:  Juergen Keck <jhyphenkeck@gmail.com>
license:     MIT
description: |
  This library wraps all functions from @Network.Wreq@ which expects a 'String'
  and replaces the 'String' Type with the "Network.Wreq.StringLess.StringLike" Type-Class.

  Instances for "Network.Wreq.StringLess.StringLike" are given for:

    * "Data.Text"
    .
    * "Data.Text.Lazy"
    .
    * "Data.ByteString.UTF8"
    .
    * "Data.ByteString.Lazy.UTF8"

  So you can use any of this types instead of 'String'.
  .
  To use this library, replace your the @wreq@ dependency from your @cabal@
  file with @wreq-stringless@ and import "Network.Wreq.StringLess" instead
  of @Network.Wreq@.

  The versions of this library correspond with the version of @wreq@.

  see <https://github.com/j-keck/wreq-stringless/tree/master/examples> for examples.

github:      j-keck/wreq-stringless
category:    Web
ghc-options: -Wall


extra-source-files:
  - README.md
  - stack.yaml
  - package.yaml
  - examples/*.hs
  - examples/package.yaml
  - examples/stack.yaml
  - examples/wreq-stringless-examples.cabal



dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - text
  - utf8-string
  - wreq == 0.5.1.0


library:
  source-dirs: src
  exposed-modules:
    - Network.Wreq.StringLess
    - Network.Wreq.StringLess.Cache
    - Network.Wreq.StringLess.Cache.Store
    - Network.Wreq.StringLess.Lens
    - Network.Wreq.StringLess.Session
    - Network.Wreq.StringLess.StringLike
    - Network.Wreq.StringLess.Types
